### ISSUE TITLE
Bump `docchecks` job runner to jammy

### ISSUE THREAD

**Issue by tigarmo** [canonical/documentation-workflows#9]
If possible, please bump the `runs-on` target for the `docchecks` to ubuntu:22.04 (jammy). It's the latest LTS but a more practical aspect of this is that it comes with Python 3.10. The current runner (focal) comes with Python 3.8 and this is an issue in my specific case due to an unfortunate confluence of factors:

- The documentation includes autogenerated class docs (using autodoc);
- The source code that autodoc parses is Python 3.8-compliant, but uses `from __future__ import annotations`;
- This future import is unfortunately not taken into account by some autodoc-related extensions (in my case, `autonamedtuple`) and it fails to parse code (`type[Bla]`) that is made valid by the future import.

I'd be happy to contribute a PR if you believe this is a good idea. Thanks!

**Comment by ru-fu** [comment]
What's your take @rkratky since you just changed that? ;)

Would it be possible to make this configurable? Run on `ubuntu-latest` by default, but make it possible for anyone that uses the workflow to specify another version?

**Comment by rkratky** [comment]
I didn't realize the Python aspect. Everyone can change this in their respective repo, but then we lose the convenience of pulling the Action definition from a central location.

My only motivation for the change was that the waiting time for 22.04/latest runners was super long, whereas 20.04 runners tend to get allocated instantly (I've no idea why that's the case).

Given that my change was an ugly hack, I've no problems with being changed back. A real solution to the provisioning problem is likely in paying more money to GH :/

**Comment by tigarmo** [comment]
Oh if the 20.04 runners start instantly I don't want to lose that :smile: . Possibly there's less contention for them.

My suggestion then is to keep 20.04 but use the [setup-python](https://github.com/actions/setup-python) action to provision Python 3.10. This would also give a clear way to add an option so that users can customize this version, if necessary.

**Comment by ru-fu** [comment]
Sounds good to me! Want to make a PR? :)
